name: Freecine Translations
highlighter: null
markdown: kramdown
paginate: 10
version: 1
seo:
  author: "Scott Schaffter - Bivee LLC"
  description: "Superb French to English Translations - focusing on international development, legal and film translation."
  keywords: 'English to French Legal Translation, Spanish to French Translation, NGOs, International Organizations, Law Firms, International Courts, Subtitling'

contact:
  phone: ''
  email: ''
  address-line1: ''
  address-line2: ''
  address-line3: ''
  map-link: ''

baseurl: /
permalink: /:title

social:
google:
  analytics : ''
  domain: ''

assets:
  img: '/assets/images/'
  css: '/assets/css/'
  js: '/assets/js/'
  logos: '/assets/images/client_logos/'

prose:
  rooturl: '_posts'
  siteurl: ''
  media: 'uploads'
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes

  metadata:
    _posts: