name: Freecine Translations
highlighter: null
markdown: kramdown
paginate: 10
version: 1
seo:
  author: "Bivee LLC"
  description: "Superb French to English Translations - focusing on international development, legal and film translation."
  keywords: 'English to French Legal Translation, Spanish to French Translation, NGOs, International Organizations, Law Firms, International Courts, Subtitling'

contact:
  name: 'Freecine Translations, LLC'
  phone: '+ 1 301 530 0893'
  email: ''
  address-line1: '9527 Ewing Drive, Bethesda MD 20817'
  address-line2: ''
  address-line3: ''
  map-link: ''

baseurl: /
permalink: /:title

social:
  linkedin: 'https://www.linkedin.com/pub/francine-le-touz%C3%A9/6/171/396'
google:
  analytics : 'UA-54754046-1'
  domain: 'www.freecinetranslations.com'

assets:
  img: '/assets/images/'
  css: '/assets/css/'
  js: '/assets/js/'
  logos: '/assets/images/uploads/'

prose:
  rooturl: '_posts'
  siteurl: 'www.freecinetranslations.com'
  media: 'media'
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
