name: Freecine Translations
highlighter: null
markdown: kramdown
paginate: 10
version: 1
seo:
  author: "Bivee LLC"
  description: "Superb French to English Translations - focusing on international development, legal and film translation."
  keywords: 'English to French Legal Translation, Spanish to French Translation, NGOs, International Organizations, Law Firms, International Courts, Subtitling'

contact:
  name: 'Freecine Translations, LLC'
  phone: '+ 1 301 530 0893'
  email: ''
  address-line1: '9527 Ewing Drive, Bethesda MD 20817'
  address-line2: ''
  address-line3: ''
  map-link: ''

baseurl: /
permalink: /:title

social:
  linkedin: 'https://www.linkedin.com/pub/francine-le-touz%C3%A9/6/171/396'
google:
  analytics : 'UA-54754046-1'
  domain: 'freecinetranslations.com'

assets:
  img: '/assets/images/'
  css: '/assets/css/'
  js: '/assets/js/'
  logos: '/assets/images/uploads/'

prose:
  rooturl: '_posts'
  siteurl: 'www.freecinetranslations.com'
  media: 'assets/images/uploads'
  ignore:
    - index.md
    - index.html
    - _config.yml
    - /_layouts
    - /_includes

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: ''
      - name: "category"
        field:
          element: "hidden"
          value: ''
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/about_you_content:
      - name: "category"
        field:
          element: "hidden"
          value: "about_you"
      - name: "layout"
        field:
          element: "hidden"
          value: "client-layout"
      - name: "subtitle"
        field:
          element: "text"
          label: "Enter a subtitle area about the client"
      - name: "logo"
        field:
          element: "text"
          label: "Enter the name of the logo image you have uploded"
          value: ''
      - name: "order"
        field:
          element: "text"
          label: "Enter the order number of the posts"
          value: ''
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/lets_talk_content:
      - name: "category"
        field:
          element: "hidden"
          value: "lets_talk"
      - name: "layout"
        field:
          element: "hidden"
          value: ''
      - name: "order"
        field:
          element: "text"
          label: "Enter the order number of the posts"
          value: ''
      - name: "icon"
        field:
          element: "text"
          value: ''
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/and_us_content/partners:
      - name: "category"
        field:
          element: "hidden"
          value: "partners"
      - name: "url"
        field:
          element: "text"
          label: "Enter the url of the partner website"
          value: ''
      - name: "logo"
        field:
          element: "text"
          label: "Enter the name of the logo image you have uploded"
          value: ''
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""